### PR TITLE
Swinging door compression: fix compression to avoid unnecessary datapoints

### LINKED ISSUE #59: Difference between the stated algorithm and other sources
Hello gfoidl,

as I am also trying to implement the Swinging door algorithm I was looking through your very helpful graphics and descriptions of the algorithm. As I was implementing it I was verifying my code against the output of your code ("erregerspannung.csv without deadband") and was also reading other resources. One thing was puzzleing for me though. You are stating that: 
image
Compared to other resources like https://softwaredocs.weatherford.com/cygnet/94/Content/Topics/History/CygNet%20Swinging%20Door%20Compression.htm or https://www.youtube.com/watch?v=89hg2mme7S0 I thought that only the last snapshot (the datapoint for the beginning for the new swinging doors) is saved and not the next datapoint which exceeds the spawned area by the swinging doors. I would be very grateful if you could clarify that a bit. Another interesting thing to know would be how you verified the correctness of your  algorithm.

Thanks in advance! 

All the best

FloCD

### PR DESCRIPTION
**Pull request by gfoidl**
Fixes https://github.com/gfoidl/DataCompression/issues/59

Due the common code-path for the core-iteration of deadband and swinging door, there was a bug which recored too much datapoints for the swinging door algorithm. This PR fixes this, by introducing a new property `ArchiveIncoming` that needs to be set on each specific algorithm.

The rest of the PR adds more tests, and shuffles some things around.

### CODE REVIEW

File: source/gfoidl.DataCompression/Compression/SwingingDoorCompression/SwingingDoorCompressionIterator.cs [hunk 1]
```diff
@@ -34,11 +34,34 @@ protected void CloseTheDoor(in DataPoint incoming, in DataPoint lastArchived)
         {
             Debug.Assert(_swingingDoorCompression is not null);
 
-            double upperSlope = lastArchived.Gradient(incoming,  _swingingDoorCompression.CompressionDeviation);
-            double lowerSlope = lastArchived.Gradient(incoming, -_swingingDoorCompression.CompressionDeviation);
+            double delta_x = incoming.X - lastArchived.X;
 
-            if (upperSlope < _slope.Max) _slope.Max = upperSlope;
-            if (lowerSlope > _slope.Min) _slope.Min = lowerSlope;
+            if (delta_x != 0)
```
Comment (gfoidl) [inline source/gfoidl.DataCompression/Compression/SwingingDoorCompression/SwingingDoorCompressionIterator.cs]:
```suggestion
            if (delta_x > 0)
```
Is this better? Can't be less than 0, so maybe this elides another jmp in the assembly.

Comment (gfoidl) [reply source/gfoidl.DataCompression/Compression/SwingingDoorCompression/SwingingDoorCompressionIterator.cs]: Yes, it is.

```diff
       vzeroupper
       lea       rdx,[rcx+30]
       lea       r8,[rcx+20]
       vmovsd    xmm0,qword ptr [rdx]
       vsubsd    xmm0,xmm0,qword ptr [r8]
       vxorps    xmm1,xmm1,xmm1
       vucomisd  xmm0,xmm1
-      jp        short M00_L00
-      je        short M00_L03
+      jbe       short M00_L03
M00_L00:
       vmovsd    xmm1,qword ptr [rdx+8]
       vsubsd    xmm1,xmm1,qword ptr [r8+8]
       mov       rdx,[rcx+8]
       vmovsd    xmm2,qword ptr [rdx+38]
       vaddsd    xmm3,xmm1,xmm2
       vdivsd    xmm3,xmm3,xmm0
       vsubsd    xmm1,xmm1,xmm2
       vdivsd    xmm0,xmm1,xmm0
       vmovsd    xmm1,qword ptr [rcx+10]
       vucomisd  xmm1,xmm3
       jbe       short M00_L01
       vmovsd    qword ptr [rcx+10],xmm3
M00_L01:
       vucomisd  xmm0,qword ptr [rcx+18]
       jbe       short M00_L02
       vmovsd    qword ptr [rcx+18],xmm0
M00_L02:
       ret
M00_L03:
       jmp       near ptr gfoidl.DataCompression.Benchmarks.SwingingDoorCompressionIteratorCloseTheDoorBenchmarks.<Inlined2>g__GradientEquality|12_0(gfoidl.DataCompression.DataPoint ByRef, gfoidl.DataCompression.DataPoint ByRef)
-; Total bytes of code 102
+; Total bytes of code 100
```

Comment (gfoidl) [reply source/gfoidl.DataCompression/Compression/SwingingDoorCompression/SwingingDoorCompressionIterator.cs]: Maybe a similar optimization should be done in https://github.com/gfoidl/DataCompression/blob/6dc1da9f3fe1a816d185b382775cce628576e60d/source/gfoidl.DataCompression/DataPoint.cs#L90-L110 too.

* flip the branch condition
* make the uncommon path a tail call jmp

**Comment by gfoidl** [comment]
@FloCD I hope the bug got fixed, can you please give it a try?

I pushed a preview-version [v2.2.0-preview-1](https://dev.azure.com/gh-gfoidl/github-Projects/_packaging?_a=package&feed=gfoidl-public%40Local&package=gfoidl.DataCompression&protocolType=NuGet&version=2.2.0-preview-1&view=overview) to the [development channel](https://github.com/gfoidl/DataCompression#development-channel).
Or if you prefer a local build:
```bash
./build.sh build
./build.sh pack

# NuGet-package is in ./NuGet-Packed
```

Thanks in advance!
